### ISSUE TITLE
Sur mac (safari ou firefox) le texte avant le braille ne s'affiche pas entièrement

### ISSUE THREAD

**Issue by stanlee974** [damiengomez/EscapeGameA11y#6]
https://damiengomez.github.io/EscapeGameA11y/2-1-simulation-visuel.html

![image](https://github.com/damiengomez/EscapeGameA11y/assets/32981008/f571bea7-83ba-4757-b78b-c193a2a299cd)

et directement après on a le braille, plutôt que la suite de l'activité

**Comment by damiengomez** [comment]
Oui le bug avait déjà été identifié, il est corrigé sur la futur version, disponible normalement d'ici 1 mois ou 2.
