### ISSUE TITLE
Sur les images de brailles, il y a des tooltips de la transcription

### ISSUE THREAD

**Issue by stanlee974** [damiengomez/EscapeGameA11y#7]
Certaines personnes utilisent la souris, même si l'activité `2-1-simulation-visuel` est au clavier. 
En supprimant la tooltip, l'utilisation du dictionnaire braille prendrait tout son sens.
Qu'est ce que tu en penses?

**Comment by damiengomez** [comment]
Quand j'anime l'escape game, j'ai toujours un jeu de dictionnaire en braille sur moi pour aider les joueurs.
Mais pour le cas ou cette aide n'est pas présente, je laisse les joueurs s'aider de google ou des tooltips si ils les trouvent ;)
ça ce discute ...

**Comment by stanlee974** [comment]
Mon contenu n'était pas complet. Du coup les personnes à la souris, survolaient le braille et avait le caractère correspondant. Si la partie déchiffrage de braille est important dans cet exercice, il faudrait enlever le tooltip. Si on s'en fiche, on peut aussi communiquer dessus au niveau de l'animation si besoin

**Comment by damiengomez** [comment]
Effectivement tu as raisons, autant supprimer ces tooltips, l'aide doit venir du maitre du jeu

**Comment by stanlee974** [comment]
j'ai mis une tooltip pour dire d'utiliser le clavier, si c'est pas bon, tu me dis et j'adapte

**Comment by stanlee974** [comment]
closed with PR https://github.com/damiengomez/EscapeGameA11y/pull/10
